# Pytorch Tutorial
<br/>
https://www.youtube.com/watch?v=exaWOE8jvy8&list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4&index=2

In [1]:
import torch

### Torch Basics

In [4]:
#empty tensor
print(torch.empty(1))
print(torch.empty(3))
print(torch.empty(2,2,2))

tensor([0.])
tensor([0., 0., 0.])
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])


In [6]:
#random values
print(torch.rand(2))
print(torch.rand(2,2))

tensor([0.0041, 0.2425])
tensor([[0.4875, 0.2441],
        [0.8190, 0.9803]])


In [13]:
#zeors
print(torch.zeros(2))
print(torch.zeros(2,2))

#ones
print(torch.ones(1))
print(torch.ones(2,2))
print(torch.ones((2,2),dtype=torch.int))

tensor([0., 0.])
tensor([[0., 0.],
        [0., 0.]])
tensor([1.])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [14]:
print(torch.tensor([1,2,3]))

tensor([1, 2, 3])


In [22]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x+y
zz = torch.add(x,y)
print(z,zz)
print(y.add_(x))

tensor([[0.4721, 0.7186],
        [0.5053, 1.1358]]) tensor([[0.4721, 0.7186],
        [0.5053, 1.1358]])
tensor([[0.4721, 0.7186],
        [0.5053, 1.1358]])


In [27]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x-y
zz = torch.sub(x,y)
print(z,zz)
print(x.sub_(y))

tensor([[-0.5756, -0.3569],
        [ 0.3848,  0.5002]]) tensor([[-0.5756, -0.3569],
        [ 0.3848,  0.5002]])
tensor([[-0.5756, -0.3569],
        [ 0.3848,  0.5002]])


In [24]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x*y
zz = torch.mul(x,y)
print(z,zz)
print(y.mul_(x))

tensor([[0.1914, 0.0646],
        [0.0135, 0.4387]]) tensor([[0.1914, 0.0646],
        [0.0135, 0.4387]])
tensor([[0.1914, 0.0646],
        [0.0135, 0.4387]])


In [26]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x/y
zz = torch.div(x,y)
print(z,zz)
print(x.div_(y))

tensor([[ 0.5499, 37.5152],
        [ 0.3481,  0.4976]]) tensor([[ 0.5499, 37.5152],
        [ 0.3481,  0.4976]])
tensor([[ 0.5499, 37.5152],
        [ 0.3481,  0.4976]])


In [34]:
x = torch.rand(5,3)
print(x)
print(x[1,1].item())
print(x[1:,:])

tensor([[0.1240, 0.3165, 0.1604],
        [0.5641, 0.2784, 0.7033],
        [0.9646, 0.2098, 0.7182],
        [0.4369, 0.5483, 0.3461],
        [0.6531, 0.3437, 0.0111]])
0.27841806411743164
tensor([[0.5641, 0.2784, 0.7033],
        [0.9646, 0.2098, 0.7182],
        [0.4369, 0.5483, 0.3461],
        [0.6531, 0.3437, 0.0111]])


In [36]:
#reshape
x = torch.rand(4,4)
print(x)
print(x.view(16))
print(x.view(-1,8))
print(x.view(2,-1))

tensor([[0.1750, 0.4590, 0.4123, 0.3579],
        [0.8230, 0.0621, 0.6219, 0.2198],
        [0.8509, 0.4130, 0.4553, 0.1162],
        [0.6068, 0.5022, 0.8484, 0.3866]])
tensor([0.1750, 0.4590, 0.4123, 0.3579, 0.8230, 0.0621, 0.6219, 0.2198, 0.8509,
        0.4130, 0.4553, 0.1162, 0.6068, 0.5022, 0.8484, 0.3866])
tensor([[0.1750, 0.4590, 0.4123, 0.3579, 0.8230, 0.0621, 0.6219, 0.2198],
        [0.8509, 0.4130, 0.4553, 0.1162, 0.6068, 0.5022, 0.8484, 0.3866]])
tensor([[0.1750, 0.4590, 0.4123, 0.3579, 0.8230, 0.0621, 0.6219, 0.2198],
        [0.8509, 0.4130, 0.4553, 0.1162, 0.6068, 0.5022, 0.8484, 0.3866]])


In [48]:
#converting to numpy and vice versa
import numpy as np
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
c = a.numpy().copy()
a.add_(a)
print(b)
print(c)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]


In [ ]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
c = torch.from_numpy(a).to(torch.int)
print(torch.tensor(a))
print(c)
print(b)
a = a +1 
print(b) #IF GPU, THE VALUE WILL BE CHANGED


[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1, 1, 1, 1, 1], dtype=torch.int32)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [ ]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    #z.numpy() throw error since these are gpu tensors
    z = z.to('cpu')
    z.numpy()

### Gradient Calculation with Autograd

In [57]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x +2

print("y:", y)

z =y*y*2

print("z", z)
z = z.mean()
print("z", z)

z.backward() # calculate gradients dz/dx
print(x.grad)
# print(y.grad)
# print(z.grad)




# Inspect the function that created y
# print("y.grad_fn:", y.grad_fn)


# #Traverse the graph backwards
# def print_graph(var):
#     print(f"\nTraversing graph for {var}")
#     fn = var.grad_fn
#     while fn:
#         print(f" -> {fn}")
#         fn = fn.next_functions[0][0] if fn.next_functions else None

# print_graph(z)

tensor([-0.9951, -0.5867,  0.3833], requires_grad=True)
y: tensor([1.0049, 1.4133, 2.3833], grad_fn=<AddBackward0>)
z tensor([ 2.0195,  3.9946, 11.3604], grad_fn=<MulBackward0>)
z tensor(5.7915, grad_fn=<MeanBackward0>)
tensor([1.3398, 1.8843, 3.1778])


In [58]:
from numpy import dtype


x = torch.randn(3, requires_grad=True)
print(x)
y = x +2

print("y:", y)

z =y*y*2

print("z", z)
# z = z.mean() # cause error
print("z", z)
v = torch.tensor([0.1, 1.0,0.001], dtype=torch.float32) # pass it make z scalar
z.backward(v) # calculate gradients dz/dx
print(x.grad)
# print(y.grad)
# print(z.grad)




# Inspect the function that created y
# print("y.grad_fn:", y.grad_fn)


# #Traverse the graph backwards
# def print_graph(var):
#     print(f"\nTraversing graph for {var}")
#     fn = var.grad_fn
#     while fn:
#         print(f" -> {fn}")
#         fn = fn.next_functions[0][0] if fn.next_functions else None

# print_graph(z)

tensor([2.0737, 0.4979, 1.0570], requires_grad=True)
y: tensor([4.0737, 2.4979, 3.0570], grad_fn=<AddBackward0>)
z tensor([33.1899, 12.4788, 18.6907], grad_fn=<MulBackward0>)
z tensor([33.1899, 12.4788, 18.6907], grad_fn=<MulBackward0>)
tensor([1.6295, 9.9915, 0.0122])


In [ ]:
x = torch.randn(3, requires_grad=True)
print(x)

# x.requires_grad_(False)
# y = x.detach()
# with torch.no_grad():


In [ ]:
#if no backward fn is called, the gradient will be accumulated



weights = torch.ones(5, requires_grad=True)

for epoch in range(3):
    output = (weights *  3).sum()
    output.backward()
    print(weights.grad)


weights = torch.ones(5, requires_grad=True)

for epoch in range(3):
    output = (weights *  3).sum()
    output.backward()
    print(weights.grad)
    weights.grad.zero_()
    

weights = torch.ones(5, requires_grad=True)
optimizer = torch.optim.SGD(weights, lr = 0.001)
optimizer.step()
optimizer.zero_grad()

tensor([3., 3., 3., 3., 3.])
tensor([6., 6., 6., 6., 6.])
tensor([9., 9., 9., 9., 9.])
tensor([3., 3., 3., 3., 3.])
tensor([3., 3., 3., 3., 3.])
tensor([3., 3., 3., 3., 3.])


### Backpropagation

In [68]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)

#forward pass and compute loss
y_hat = w * x
loss = (y_hat - y)**2

print(loss)

loss.backward()
print(w.grad)


tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
